{
   "jobs" : {
      "build" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/build"
         },
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "make test-deps"
               }
            },
            {
               "run" : {
                  "command" : "make test"
               }
            },
            {
               "run" : {
                  "background" : true,
                  "command" : "USE_XFF=1 ./plackup -p 5114 -t Twiggy::Prefork support/server.psgi 2>&1 > serverlog"
               }
            },
            {
               "run" : {
                  "command" : "sleep 10"
               }
            },
            {
               "run" : {
                  "command" : "curl -f http://0:5114 || (cat serverlog && false)"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/build"
               }
            },
            {
               "deploy" : {
                  "command" : "if [ \u0022${CIRCLE_BRANCH}\u0022 == 'heroku' ]; then\u000Atrue\u000Amake deploy-heroku\u000Afi"
               }
            }
         ]
      }
   },
   "version" : 2,
   "workflows" : {
      "build" : {
         "jobs" : [
            {
               "build" : {
               }
            }
         ]
      },
      "version" : 2
   }
}
