#!/usr/bin/perl
print <<EOH;
Content-Type: text/plain
Last-Modified: 01 Jan 2020 00:00:00 GMT

EOH
    for (sort qw/SERVER_PROTOCOL SERVER_NAME SERVER_PORT SERVER_SOFTWARE GATEWAY_INTERFACE REQUEST_METHOD PATH_INFO QUERY_STRING REMOTE_ADDR REMOTE_HOST REMOTE_USER REMOTE_IDENT CONTENT_TYPE CONTENT_LENGTH HTTP_CONTENT_TYPE AUTH_TYPE HTTP_CONTENT_LENGTH REQUEST_URI SCRIPT_NAME/, grep /^HTTP_/, keys %ENV) {
        print "$_: $ENV{$_}\n";
    }
